custom_cms:
    resource: "@CustomCMSBundle/Controller/"
    type:     annotation
    prefix:   /cms

custom_cms_user:
    resource: "@CustomCMSBundle/Resources/config/routing/user.yml"
    prefix:   /cms/user

custom_cms_category:
    resource: "@CustomCMSBundle/Resources/config/routing/category.yml"
    prefix:   /cms/category    

custom_cms_cms_page:
    resource: "@CustomCMSBundle/Resources/config/routing/page.yml"
    prefix:   /cms/page    

login:
    path: /cms/login
    defaults: { _controller: CustomCMSBundle:Security:login }

# login_check:
#     path: /login_check

logout:
    pattern: /cms/logout
    
lynda_magazine:
    resource: "@LyndaMagazineBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
