<?php

namespace Custom\CMSBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Get last pages created
	 *
	 * @param  integer $max number of pages to return
	 * @return Page[]
	 */
	public function getLatestPages($max = 3)
	{
		return $this->createQueryBuilder('p')
					->addOrderBy('p.id', 'DESC')
				    ->setMaxResults( $max )
			        ->getQuery()
			        ->execute();
	}
}
