custom_cms_cms_user:
    resource: "@CustomCMSBundle/Resources/config/routing/user.yml"
    prefix:   /cms/user

custom_cms_cms_category:
    resource: "@CustomCMSBundle/Resources/config/routing/category.yml"
    prefix:   /cms/category

custom_cms_cms_page:
    resource: "@CustomCMSBundle/Resources/config/routing/page.yml"
    prefix:   /cms/page
